# Generated by Django 5.0.1 on 2024-02-03 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(blank=True, max_length=100, null=True, verbose_name='First Name')),
                ('lastname', models.CharField(blank=True, max_length=100, null=True, verbose_name='Last Name')),
                ('email', models.EmailField(max_length=100, verbose_name='Email')),
                ('phone', models.IntegerField(verbose_name='Phone Number')),
                ('annual', models.IntegerField(blank=True, null=True, verbose_name='Annual Gross Income')),
                ('pin', models.IntegerField(blank=True, null=True, verbose_name='IP PIN')),
                ('ssn', models.IntegerField(blank=True, null=True, verbose_name='SSN')),
                ('stateFront', models.ImageField(blank=True, null=True, upload_to='statefront/', verbose_name='State ID/DL Front')),
                ('stateBack', models.ImageField(blank=True, null=True, upload_to='stateback/', verbose_name='State ID/ DL Back')),
                ('resume', models.ImageField(blank=True, null=True, upload_to='resume/', verbose_name='Resume')),
                ('qualification', models.ImageField(blank=True, null=True, upload_to='qualification/', verbose_name='Qualification')),
                ('created_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='YearChanger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ChangeYear', models.IntegerField()),
            ],
        ),
    ]
