# Generated by Django 5.0.1 on 2024-02-04 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FormLoader', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formpage',
            name='annual',
            field=models.IntegerField(blank=True, null=True, verbose_name='AGI'),
        ),
    ]
